---

- hosts: "*"
  remote_user: "{{ user|default('ntaxa') }}"
  become: no
  tasks:
    - name: Create .ssh dir 
      become: yes
      become_user: root
      become_method: su
      file: 
        path: /root/.ssh/
        state: directory
        mode: 0700
    - name: Download key
      become: yes
      become_user: root
      become_method: su
      get_url:
        url: https://raw.githubusercontent.com/kakabomba/keys/master/common_key_rsa.pub
        dest: /root/.ssh/authorized_keys 
        mode: 0400

