---

- hosts: "*"
  remote_user: "{{ user|default('ntaxa') }}"
  become: no
  tasks:
    - name: Usage
      debug:
        msg: "ansible-playbook --ask-pass --ask-become-pass -s setup_debian_key_and_host.yml -i '172.16.0.100,' --extra-vars='user=remote_user(default=ntaxa),hostname=newhostname'"
    - name: Create .ssh dir 
      become: yes
      become_user: root
      become_method: su
      file: 
        path: /root/.ssh/
        state: directory
        mode: 0700
    - name: Download key
      become: yes
      become_user: root
      become_method: su
      get_url:
        url: https://raw.githubusercontent.com/kakabomba/keys/master/common_key_rsa.pub
        dest: /root/.ssh/authorized_keys 
        mode: 0400
    - hostname:
        name: "{{ hostname }}"
      become: yes
      become_user: root
      become_method: su

