---

- hosts: "{{ host }}"
  remote_user: root
  tasks:
    - name: Update repositories cache
      debug:
        msg: "ansible-playbook -s /home/oles/playbook/proxmox_copy_worker.yml --extra-vars \"host=p \""
    - name: test proxmox connection
      proxmox_kvm:
        api_user    : 'root@pam'
        api_password: ''
        api_host    : "p.ntaxa.com"
        name        : dns
        node        : profireader
        vmid        : 100
        state       : current
#    - name: Update repositories cache
#      proxmox_kvm:
#        api_user    : root@pam
#        api_password: secret
#        api_host    : "p.ntaxa.com:8006"
#        clone       : "{{ source_name|default('template-debian-8') }}"
#        name        : "{{ target_name }}"
#        newid	    : "{{ target_id }}"
#        net	        : '{"mac":"FF:FF:10:10:{{target_id[0:2]}}:{{target_id[2:4]}}"}'
#        node        : profireader
#        storage     : images
#        format      : raw
#        cpu         : "{{ cpu|default('1') }}"
#        memory      : "{{ (memory|default('0.5')|int)*1024 }}"
#        timeout     : 6000  # Note: The task can take a while. Adapt
#
