---

- name: copy scripts
  copy:
    src: "{{role_path}}/templates/scripts/"
    mode: preserve
    force: yes
    dest: "/"

- name: replace
  replace:
    path: /usr/local/bin/ntaxa-haproxy-generate-config-from-workers.sh
    regexp: "ip_net_domain_sets='.*'"
    replace: "ip_net_domain_sets='{{ ip_net_domain_sets }}'"

- name: Set haproxy key to run command '/usr/local/bin/ntaxa-haproxy-generate-config-from-workers.sh' from workers
  authorized_key:
    user: root
    state: present
    key: "no-port-forwarding,no-X11-forwarding,no-pty,command=\"/usr/local/bin/ntaxa-haproxy-generate-config-from-workers.sh\" {{ lookup('file', playbook_dir + '/../roles/haproxy-for-workers/templates/scripts/root/.ssh/haproxy_worker_communication_id_rsa.pub') }}"

- name: restart cron
  service:
    name: cron
    state: restarted

