---

- name: copy scripts
  copy:
    src: "{{role_path}}/templates/scripts/"
    mode: preserve
    force: yes
    dest: "/"

- name: replace
  replace:
    path: /usr/local/bin/ntaxa-haproxy-generate-config-from-workers.sh
    regexp: "ip_net_domain_sets=''"
    replace: "ip_net_domain_sets='{{ ip_net_domain_sets }}'"


#- name: replace
#  replace:
#    path: /usr/local/bin/ntaxa-haproxy-generate-config-from-workers.sh
#    regexp: "ip_net_domain_sets=''"
#    replace: "ip_net_domain_sets='{{ ip_net_domain_sets }}'"

