---

- name: copy scripts
  copy:
    src: "{{role_path}}/templates/scripts/"
    mode: preserve
    force: yes
    dest: "/"

- name: replace
  replace:
    path: /usr/local/bin/ntaxa-haproxy-generate-config-from-workers.sh
    regexp: "ip_net_domain_sets='.*'"
    replace: "ip_net_domain_sets='{{ ip_net_domain_sets }}'"

- name: Ensure .ssh directory exists.
  file:
    dest: "/root/.ssh"
    mode: 0700
    owner: root
    state: directory

- name: Install ssh key
  copy:
    content: "{{ haproxy_worker_communication_id_rsa }}"
    dest: "/root/.ssh/haproxy_worker_communication_id_rsa"
    mode: 0600
    owner: root

- name: restart cron
  service:
    name: cron
    state: restarted
