---

- name: copy scripts
  copy:
    src: "{{role_path}}/templates/scripts/"
    mode: preserve
    dest: "/"

- name: Install common packages
  apt:
    name: "{{ item }}"
  with_items:
    - openvpn

#- iptables:
#    chain: FORWARD
#    ctstate: NEW,ESTABLISHED,RELATED
#    jump: ACCEPT
#  become: yes

- sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: reload openvpn
  service:
    name: openvpn
    state: restarted
