- name: Update apt cache
  apt:
    update_cache: yes
  ignore_errors: yes

- name: Install common packages
  apt:
    name: "{{ item }}"
  with_items:
    - vim
    - vim-python-jedi
    - zsh
    - mc
    - ssh
    - git
    - build-essential
    - sudo
    - nmap
    - curl
    - bzip2
    - pv
    - software-properties-common
    - tcpdump
    - links
    - lynx
    - debconf-utils
    - python-pip
    - jq
    - colordiff
    - iptables-persistent
    - net-tools
    - imagemagick
    - zip
    - kpartx
    - docker
    - docker-compose
    - cifs-utils

- name: Generate locales
  shell: locale-gen "en_US" && locale-gen "en_US.UTF-8" && locale-gen "uk_UA.UTF-8"

- name: Install oh-my-zhs (best shell needs braces)
  shell: curl -L http://install.ohmyz.sh | sh

- name: copy scripts
  copy:
    src: "{{role_path}}/templates/scripts/"
    mode: preserve
    dest: "/"

- name: remove .zshrc file from root directory
  file:
    dest: /root/.zshrc
    state: absent
    
- name: remove .zshrc file from root directory
  file:
    dest: "/home/{{ sudo_user }}/.zshrc"
    state: absent
  when: sudo_user is defined
    
- name: copy root script to another user (sudo_user)
  copy:
    src: "{{role_path}}/templates/scripts/root/"
    mode: preserve
    owner: "{{ sudo_user }}"
    group: "{{ sudo_user_group }}"
    dest: "/home/{{ sudo_user }}/"
  when: sudo_user is defined
    
- name: change shell for user oles
  user:
    name: "{{ sudo_user }}"
    shell: /usr/bin/zsh
  when: sudo_user is defined
    
- name: Copy files .oh-my-zhs
  shell: "if [ ! -d /etc/zsh/.oh-my-zsh ]; then mv /root/.oh-my-zsh /etc/zsh/; fi"

- name: install zsh-syntax-highlighting (best shell braces also need braces)
  git:
    repo: 'git://github.com/zsh-users/zsh-syntax-highlighting.git'
    accept_hostkey: true
    dest: /etc/zsh/zsh-syntax-highlighting

- name: "change zsh theme"
  lineinfile:
    path: /etc/zsh/zshrc
    regexp: '^\s*export ZSH_THEME="[^"]+".*'
    line: 'export ZSH_THEME="{{ zsh.theme }}"'
  when: zsh is defined and zsh.theme is defined

- name: "change zsh prompt"
  lineinfile:
    path: /etc/zsh/zshrc
    regexp: "^\\s*PROMPT='.*"
    line: "PROMPT='{{ zsh.prompt }}'"
  when: zsh is defined and zsh.prompt is defined and zsh.prompt

- name: "comment zsh prompt"
  lineinfile:
    path: /etc/zsh/zshrc
    regexp: "^\\s*PROMPT='.*"
    state: absent
  when: zsh is defined and zsh.prompt is defined and not zsh.prompt
