---

- hosts: "{{ hosts|default('*') }}"
  gather_facts: False
  remote_user: root
  become: no
  serial: 4
  tasks:

#  - name: Remove "postfix" package
#    apt:
#      name: postfix
#      state: absent


#  - name: Copy haproxy private key
#    copy:
#      src: "{{ playbook_dir }}/../roles/haproxy-for-workers/templates/scripts/root/.ssh/haproxy_worker_communication_id_rsa"
#      dest: /root/.ssh/
#      owner: root
#      group: root
#      mode: 0400

  - name: Copy script
    copy:
      src: "{{ playbook_dir }}/../roles/worker/templates/scripts/usr/local/bin/ntaxa-apache-list-projects.sh"
      dest: /usr/local/bin/
      owner: root
      group: root
      mode: 0755

  - name: Copy script
    copy:
      src: "{{ playbook_dir }}/../roles/common/templates/scripts/usr/local/bin/o-lib.sh"
      dest: /usr/local/bin/
      owner: root
      group: root
      mode: 0755
#
#  - name: Copy script
#    copy:
#      src: "{{ playbook_dir }}/../roles/worker/templates/scripts/usr/local/bin/ntaxa-apache-remove-project.sh"
#      dest: /usr/local/bin/
#      owner: root
#      group: root
#      mode: 0755


############################################################
#  - name: set ftp user isolation
#    copy:
#      content: "yes\n"
#      dest: /etc/pure-ftpd/conf/ChrootEveryone
#      force: yes
#      group: root
#      owner: root
#
#  - name: reload pureftp
#    service:
#      name: pure-ftpd-mysql
#      state: restarted


############################################################
#  - copy:
#      src: "{{ playbook_dir }}/../roles/worker/templates/scripts/usr/local/bin/"
#      dest: /usr/local/bin/
#      owner: root
#      group: root
#      mode: 0755

#  - name: set minimum user id
#    copy:
#      content: "32\n"
#      dest: /etc/pure-ftpd/conf/MinUID
#      force: yes
#      group: root
#      owner: root
#
#  - name: reload pureftp
#    service:
#      name: pure-ftpd-mysql
#      state: restarted


############################################################
#  - file:
#      path: /etc/cron.daily/mlocate
#      state: absent
#
#  - name: reload cron
#    service:
#      name: cron
#      state: restarted

  - ping: