---

- hosts: "{{ hosts|default('*') }}"
  remote_user: root
  become: no
  gather_facts: False
  tasks:
    - name: Usage
      debug:
        msg: ""
    - name: fetch
      fetch: dest=/tmp/zshrc-{{ source }} src=/etc/zsh/zshrc flat=yes
      when: inventory_hostname == source
    - name: copy file to remote hosts
      copy: src=/tmp/zshrc-{{ source }} dest=/etc/zsh/zshrc
      when: inventory_hostname != source
